@LocationSystem.Api_HostAddress = http://localhost:5231

###DentalOffices 新增
POST {{LocationSystem.Api_HostAddress}}/api/DentalOffices
Accept: application/json
Content-Type: application/json

{
  "name":"新的DetalOffices"
}
###
GET {{LocationSystem.Api_HostAddress}}/api/DentalOffices
Accept: application/json


### Patients分页
GET {{LocationSystem.Api_HostAddress}}/api/Patients
Accept: application/json

{
   "params": {
     "page":1,
     "pageSize":10,
     "keyword":""
   }
}

###编辑DentalOffices
PUT {{LocationSystem.Api_HostAddress}}/api/DentalOffices/ceda72b8-c28f-417b-ba68-8605bddf5cf0
Accept: application/json
Content-Type: application/json

{
  "name":"新的DetalOffices"
}

###删除DentalOffices
DELETE {{LocationSystem.Api_HostAddress}}/api/DentalOffices/ceda72b8-c28f-417b-ba68-8605bddf5cf0
Accept: application/json

### Patients 新增
POST {{LocationSystem.Api_HostAddress}}/api/Patients
Accept:application/json
Content-Type:application/json

{
  "name":"Patients",
  "email":"qer@mail.com"
}

### Patients 分页
GET {{LocationSystem.Api_HostAddress}}/api/Patients?page=1&pagesize=10&keyword=
Accept:application/json


### Patients获取
GET {{LocationSystem.Api_HostAddress}}/api/Patients/c1ae2d46-d87c-4742-9db4-2f6b7f53fab8
Accept:application/json

### 编辑Patients
PUT {{LocationSystem.Api_HostAddress}}/api/Patients/c1ae2d46-d87c-4742-9db4-2f6b7f53fab8
Accept:application/json
Content-Type:application/json

{
  "name":"new Patients",
  "email":"new qer@mail.com"
}
###删除Patients
DELETE {{LocationSystem.Api_HostAddress}}/api/Patients/c85179a2-b380-47f2-b7a3-aad3055a6322
Accept:application/json

### 查询单个Appointments
GET {{LocationSystem.Api_HostAddress}}}/api/Appointments
Accept:application/json
Content-Tyoe:application/json

{
  "params":""
}

### 查询AppointmentsList
GET {{LocationSystem.Api_HostAddress}}}/api/Appointments
Accept:application/json
Content-Tyoe:application/json

{
  "params":{
    "page":1,
    "pageSize":10,
    "keyWord":""
  }
}


###
POST {{LocationSystem.Api_HostAddress}}/api/Appointments
Accept:application/json
Content-Tyoe:application/json

{
  "patientId": "9db4656e-c80c-47e6-b89d-3ccf7b54f571",
  "dentistId": "8292a0a0-5814-40db-8bdc-02ebc2b723d8",
  "dentalOfficeId": "c4a98f99-9ef8-4e0d-ac4d-585d21a9c678",
  "startDate": "2025-12-13T20:44:39.740Z",
  "endDate": "2025-12-13T21:44:39.740Z"
}

### 
GET {{LocationSystem.Api_HostAddress}}/api/Appointments?page=1&pageSize=10
Accept:application/json