@LocationSystem.Api_HostAddress = http://localhost:5231

POST {{LocationSystem.Api_HostAddress}}/api/DentalOffices
Accept: application/json
Content-Type: application/json

{
  "name":"新的DetalOffices"
}
###
GET {{LocationSystem.Api_HostAddress}}/api/Patients?Page=1&PageSize=10&keywrod=
Accept: application/json

###
GET {{LocationSystem.Api_HostAddress}}/api/Patients
Accept: application/json

{
   "params": {
     "page":1,
     "pageSize":10,
     "keyword":""
   }
}

###
PUT {{LocationSystem.Api_HostAddress}}/api/DentalOffices/ceda72b8-c28f-417b-ba68-8605bddf5cf0
Accept: application/json
Content-Type: application/json

{
  "name":"新的DetalOffices"
}

###
DELETE {{LocationSystem.Api_HostAddress}}/api/DentalOffices/ceda72b8-c28f-417b-ba68-8605bddf5cf0
Accept: application/json

### Patients
POST {{LocationSystem.Api_HostAddress}}/api/Patients
Accept:application/json
Content-Type:application/json

{
  "name":"Patients",
  "email":"qer@mail.com"
}

### Patients
GET {{LocationSystem.Api_HostAddress}}/api/Patients?page=1&pagesize=10&keyword=
Accept:application/json


### Patients
GET {{LocationSystem.Api_HostAddress}}/api/Patients/c1ae2d46-d87c-4742-9db4-2f6b7f53fab8
Accept:application/json

### 编辑
PUT {{LocationSystem.Api_HostAddress}}/api/Patients/c1ae2d46-d87c-4742-9db4-2f6b7f53fab8
Accept:application/json
Content-Type:application/json

{
  "name":"new Patients",
  "email":"new qer@mail.com"
}
###
DELETE {{LocationSystem.Api_HostAddress}}/api/Patients/c85179a2-b380-47f2-b7a3-aad3055a6322
Accept:application/json